// MOSTRAR DATOS
GET http://localhost:8000/mascotas/mostrar HTTP/1.1

###
// CREAR DATOS
POST http://localhost:8000/mascotas/crear HTTP/1.1
Content-Type: application/json

{
    "nombre":"Perla",
    "tipo":"Gato",
    "edad":1,
    "raza":"Asiatico",
    "estado_adopcion":"Disponible"

}
###
// BUSCAR POR ID
GET http://localhost:8000/mascotas/buscar/1 HTTP/1.1

###
// ACTUALIZAR DATOS
PUT http://localhost:8000/mascotas/actualizar/3 HTTP/1.1
Content-Type: application/json

{
   "nombre":"Max",
    "tipo":"Perro",
    "edad":1,
    "raza":"Pitbul",
    "estado_adopcion":"Disponible"
}

###
// ELIMINAR DATOS
DELETE http://localhost:8000/mascotas/eliminar/5 HTTP/1.1
